version: 0.2

phases:
  pre_build:
    commands:
      - echo Build configuration started on `date`
  build:
    commands:
      - echo Build started on `date`
      - bin/build.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
    files:
      - '**/*'
    base-directory: 'dist'